# Generated by Django 3.0.6 on 2020-05-27 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('summary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_name', models.CharField(max_length=50)),
                ('stock_ticker', models.CharField(max_length=5)),
                ('stock_description', models.TextField(max_length=5000)),
                ('price_date', models.DateTimeField(verbose_name='price date')),
            ],
        ),
        migrations.RemoveField(
            model_name='pricetoearnings',
            name='pe_reatio',
        ),
        migrations.AddField(
            model_name='pricetoearnings',
            name='pe_ratio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='earningspershare',
            name='eps',
            field=models.DecimalField(decimal_places=2, max_digits=200),
        ),
        migrations.AlterField(
            model_name='enterprisevalue',
            name='enterprise_value',
            field=models.DecimalField(decimal_places=2, max_digits=200),
        ),
        migrations.AlterField(
            model_name='marketcap',
            name='market_cap',
            field=models.DecimalField(decimal_places=2, max_digits=200),
        ),
        migrations.AlterField(
            model_name='openprice',
            name='open_price',
            field=models.DecimalField(decimal_places=2, max_digits=200),
        ),
        migrations.AlterField(
            model_name='previousclose',
            name='previous_close',
            field=models.DecimalField(decimal_places=2, max_digits=200),
        ),
        migrations.CreateModel(
            name='StockInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique ID for this particular stock across whole platform', primary_key=True, serialize=False)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('stock', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='summary.Stock')),
            ],
        ),
        migrations.AddField(
            model_name='stock',
            name='enterprise_value',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='summary.EnterpriseValue'),
        ),
        migrations.AddField(
            model_name='stock',
            name='eps',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='summary.EarningsPerShare'),
        ),
        migrations.AddField(
            model_name='stock',
            name='market_cap',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='summary.MarketCap'),
        ),
        migrations.AddField(
            model_name='stock',
            name='open_price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='summary.OpenPrice'),
        ),
        migrations.AddField(
            model_name='stock',
            name='pe_ratio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='summary.PriceToEarnings'),
        ),
        migrations.AddField(
            model_name='stock',
            name='previous_close',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='summary.PreviousClose'),
        ),
    ]
